import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export async function downloadAsZip(html: string, filename: string = 'draftly-ui') {
  try {
    const zip = new JSZip();
    
    // Add the HTML file
    zip.file(`${filename}.html`, html);
    
    // Add the code as .txt file
    zip.file(`${filename}-code.txt`, html);
    
    // Add a README file with instructions
    const readme = `# ${filename}

## Generated by Draftly

This UI was generated using Draftly's AI-powered design system.

### Files Included

1. **${filename}.html** - Open this in your browser to view the design
2. **${filename}-code.txt** - The source code in plain text format
3. **README.md** - This file

### How to Use

1. Open \`${filename}.html\` in your browser to view the design
2. Open \`${filename}-code.txt\` to view/copy the source code
3. The HTML file includes:
   - Tailwind CSS (via CDN)
   - Google Fonts (Space Grotesk)
   - Fully responsive design
   - Production-ready code
   - Real images from Unsplash

### Customization

You can customize the design by:
- Editing colors in the HTML file
- Modifying Tailwind classes
- Adding your own custom CSS in the <style> tag
- Replacing Unsplash images with your own
- Integrating with your backend/framework

### Need Help?

Visit https://draftly.com for more information and support.

---
Generated on ${new Date().toLocaleString()}
`;
    
    zip.file('README.md', readme);
    
    // Generate the ZIP file
    const blob = await zip.generateAsync({ type: 'blob' });
    
    // Download the file
    saveAs(blob, `${filename}.zip`);
    
    return true;
  } catch (error) {
    console.error('Error creating ZIP:', error);
    return false;
  }
}

// Download code as .txt file
export function downloadAsText(html: string, filename: string = 'draftly-ui-code.txt') {
  try {
    const blob = new Blob([html], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, filename);
    return true;
  } catch (error) {
    console.error('Error downloading text:', error);
    return false;
  }
}

export function downloadHTML(html: string, filename: string = 'draftly-ui.html') {
  try {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    saveAs(blob, filename);
    return true;
  } catch (error) {
    console.error('Error downloading HTML:', error);
    return false;
  }
}

